apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-worker-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: hostpath
  hostPath:
    path: "/host_mnt/e/k8s_storage"
#  nodeAffinity:
#    required:
#      nodeSelectorTerms:
#      - matchExpressions:
#        - key: kubernetes.io/hostname
#          operator: In
#          values:
#          - minikube
